// "Карикатура" topic: history cartoons. Lives only on the server, because it contains the correct options.
// correct: 0 = A, 1 = B, 2 = C, 3 = D (answer key from the admin)
module.exports = [
  { id: "cartoon05", img: "/img/cartoons/c05.jpg", correct: 2,
    q: { tj: "Дар ин плакат Владимир Ленин бо ҷорӯб тасвир шудааст. Ин плакат чӣ паёмеро мерасонад?",
         ru: "На данном плакате изображён Владимир Ленин с метлой. Какое послание передаёт этот плакат?",
         en: "This poster shows Vladimir Lenin with a broom. What message does it convey?" },
    opts: { tj: ["Дастгирии монархия", "Мубориза бо бесаводӣ", "Тоза кардани кишвар аз низоми кӯҳна ва мухолифони он", "Рушди саноат"],
            ru: ["Поддержка монархии", "Борьба с неграмотностью", "Очищение страны от старого порядка и его противников", "Развитие промышленности"],
            en: ["Support for the monarchy", "Fighting illiteracy", "Sweeping the country clean of the old order and its opponents", "Industrial development"] } },
  { id: "cartoon07", img: "/img/cartoons/c07.jpg", correct: 2,
    q: { tj: "«Компромати каду» ва карикатураҳо бар зидди таҳдиди ядроӣ барои таблиғоти кадом кишвар дар давраи ҷанги сард хос буданд?",
         ru: "«Тыквенный компромат» и карикатуры против ядерной угрозы были характерны для пропаганды какой страны во время холодной войны?",
         en: "The “pumpkin papers” and cartoons about the nuclear threat were typical of which country's propaganda during the Cold War?" },
    opts: { tj: ["ИМА", "Британияи Кабир", "Иттиҳоди Шӯравӣ", "Фаронса"],
            ru: ["США", "Великобритании", "Советского Союза", "Франции"],
            en: ["The USA", "Great Britain", "The Soviet Union", "France"] } },
  { id: "cartoon08", img: "/img/cartoons/c08.jpg", correct: 0,
    q: { tj: "Карикатураи «The Crime of the Ages» («Ҷинояти асрҳо») аз Ҷон Маккатчен нишон медиҳад, ки давлатҳои Аврупо якдигарро дар оғози ҷанг айбдор мекунанд. Ин карикатура ба кадом воқеа марбут аст?",
         ru: "Карикатура «The Crime of the Ages» (Преступление веков) — Джон Маккатчен о том, как европейские державы обвиняют друг друга в развязывании войны. К какому событию относится эта карикатура?",
         en: "“The Crime of the Ages” by John McCutcheon shows the European powers blaming each other for starting the war. Which event is it about?" },
    opts: { tj: ["Ҷанги якуми ҷаҳонӣ", "Ҷанги дуюми ҷаҳонӣ", "Ҷанги Қрим", "Ҷанги Фаронсаву Пруссия"],
            ru: ["Первая мировая война", "Вторая мировая война", "Крымская война", "Франко-прусская война"],
            en: ["World War I", "World War II", "The Crimean War", "The Franco-Prussian War"] } },
  { id: "cartoon09", img: "/img/cartoons/c09.jpg", correct: 1,
    q: { tj: "Карикатураи «Peace and Future Cannon Fodder» («Сулҳ ва гӯшти тӯпи оянда») — расми Уилл Дайсон (1919), ки дар он Клемансо кӯдаки гирёнро бо навиштаҷоти «Даъвати соли 1940» мебинад. Ин карикатура чӣ паём дорад?",
         ru: "Карикатура «Peace and Future Cannon Fodder» (Мир и будущее пушечное мясо) — рисунок Уилла Дайсона (1919), где Клемансо видит плачущего ребёнка с надписью «Призыв 1940 года». Какой посыл передаёт эта карикатура?",
         en: "“Peace and Future Cannon Fodder” by Will Dyson (1919): Clemenceau sees a crying child labelled “1940 Class”. What is the message?" },
    opts: { tj: ["Шартномаҳои сулҳ ҷангро то абад пешгирӣ мекунанд", "Пас аз ҷанг наслҳои оянда боз маҷбур мешаванд ҷанг кунанд", "Аврупо метавонад аз хизмати ҳарбӣ комилан халос шавад", "Клемансо афзудани артишро дастгирӣ мекунад"],
            ru: ["Мирные договоры предотвращают войны навсегда", "После войны будущие поколения всё равно будут вынуждены воевать", "Европа сможет полностью избежать воинской службы", "Клемансо поддерживает увеличение армии"],
            en: ["Peace treaties prevent wars forever", "After the war, future generations will still be forced to fight", "Europe will be able to avoid military service entirely", "Clemenceau supports a bigger army"] } },
  { id: "cartoon10", img: "/img/cartoons/c10.jpg", correct: 1,
    q: { tj: "Карикатураи «The Wedding of the Century» («Тӯйи аср») дар мавзӯи иттифоқи Олмон ва ИҶШС дар соли 1939 аст. Ин карикатура кадом фикрро ифода мекунад?",
         ru: "Карикатура «The Wedding of the Century» (Свадьба века) — это вариация на тему союза Германии и СССР в 1939 году. Какую идею передаёт эта карикатура?",
         en: "“The Wedding of the Century” is a take on the 1939 German–Soviet pact. What idea does it convey?" },
    opts: { tj: ["Иттифоқи дарозмуддат ва боэътимоди Олмон ва ИҶШС", "Ҳамкории бешармона ва муваққатии ду рақиб", "Наздикшавии фарҳангии Олмон ва ИҶШС", "Дастгирии ҷомеаи ҷаҳонӣ аз ин иттифоқ"],
            ru: ["Долгосрочный и надёжный союз Германии и СССР", "Циничное и временное сотрудничество двух противников", "Культурное сближение Германии и СССР", "Поддержку мировой общественности этого союза"],
            en: ["A long-term, reliable German–Soviet alliance", "Cynical, temporary cooperation between two enemies", "Cultural rapprochement between Germany and the USSR", "World support for this alliance"] } },
  { id: "cartoon11", img: "/img/cartoons/c11.jpg", correct: 1,
    q: { tj: "Карикатураи «Very Well, Alone» («Хуб, танҳо бошем танҳо») аз Дэвид Лоу: сарбози бритониёӣ дар соҳили Ла-Манш пас аз суқути Фаронса. Ин карикатура чӣ паём дорад?",
         ru: "Карикатура «Very Well, Alone» (Ну что ж, одни так одни) — Дэвид Лоу, британский солдат на берегу Ла-Манша после падения Франции. Какой посыл передаёт эта карикатура?",
         en: "“Very Well, Alone” by David Low: a British soldier on the Channel coast after the fall of France. What is the message?" },
    opts: { tj: ["Британия умеди пирӯзиро комилан аз даст медиҳад", "Британия танҳо мемонад, вале омода аст муборизаро идома диҳад", "Вақти бо Олмон сулҳ бастан расидааст", "Британия иттифоқчиёнро дар хиёнат айбдор мекунад"],
            ru: ["Британия полностью теряет надежду на победу", "Британия остаётся в одиночестве, но готова продолжать борьбу", "Пора заключить мир с Германией", "Британия обвиняет союзников в предательстве"],
            en: ["Britain loses all hope of victory", "Britain is left alone but ready to fight on", "It is time to make peace with Germany", "Britain accuses its allies of betrayal"] } },
  { id: "cartoon12", img: "/img/cartoons/c12.jpg", correct: 0,
    q: { tj: "Карикатураи «Тамоми Аврупо дар як бистар» — карикатураҳои таблиғотии Олмон бар зидди эътилофи зидди Гитлер. Ин карикатура кадом фикрро ифода мекунад?",
         ru: "Карикатура «Вся Европа в одной постели» — немецкие пропагандистские карикатуры против антигитлеровской коалиции. Какую идею передаёт эта карикатура?",
         en: "“All of Europe in one bed” — German propaganda cartoons against the anti-Hitler coalition. What idea does it convey?" },
    opts: { tj: ["Эътилофи зидди Гитлер иттифоқи ғайритабиӣ ва дурӯягона аст", "Кишварҳои эътилоф Аврупоро тақсим мекунанд", "Роҳбарони иттифоқчиён таҳти назорати ИМА ҳастанд", "Аврупо ихтиёран Олмонро дастгирӣ мекунад"],
            ru: ["Антигитлеровская коалиция — неестественный и лицемерный союз", "Страны коалиции делят Европу", "Лидеры союзников находятся под контролем США", "Европа добровольно поддерживает Германию"],
            en: ["The anti-Hitler coalition is an unnatural, hypocritical alliance", "The coalition countries are dividing Europe", "Allied leaders are controlled by the USA", "Europe willingly supports Germany"] } },
  { id: "cartoon13", img: "/img/cartoons/c13.jpg", correct: 1,
    q: { tj: "Карикатураи «Суди таърих» — карикатураҳо дар бораи мурофиаи Нюрнберг. Ин карикатура кадом фикрро ифода мекунад?",
         ru: "Карикатура «Суд истории» — карикатуры на Нюрнбергский процесс. Какую идею передаёт эта карикатура?",
         en: "“The Judgment of History” — cartoons about the Nuremberg trials. What idea does it convey?" },
    opts: { tj: ["Ғолибон варианти худро аз таърих таҳмил мекунанд", "Ҷиноятҳои фашистӣ ҷазои сазовор мегиранд", "Мурофиаи Нюрнберг интиқоми сиёсӣ аст", "Суди таърих аз ҳама гуна судҳои байналмилалӣ муҳимтар аст"],
            ru: ["Победители навязывают свою версию истории", "Нацистские преступления получают заслуженное наказание", "Нюрнбергский процесс — это политическая месть", "Суд истории важнее любых международных судов"],
            en: ["The victors impose their version of history", "Nazi crimes receive the punishment they deserve", "The Nuremberg trials are political revenge", "History's judgment matters more than any international court"] } },
  { id: "cartoon14", img: "/img/cartoons/c14.jpg", correct: 1,
    q: { tj: "Карикатураи «The Marshall Plan Basket» («Сабади Нақшаи Маршалл») — расмҳои амрикоӣ дар бораи наҷоти Аврупои гурусна. Ин карикатура кадом фикрро ифода мекунад?",
         ru: "Карикатура «The Marshall Plan Basket» (Корзина Плана Маршалла) — американские рисунки о спасении голодающей Европы. Какую идею передаёт эта карикатура?",
         en: "“The Marshall Plan Basket” — American drawings about rescuing hungry Europe. What idea does it convey?" },
    opts: { tj: ["Аврупо бо бӯҳрони баъдиҷангӣ мустақилона мубориза мебарад", "ИМА ба Аврупо барои барқарор кардани он кӯмаки иқтисодӣ мерасонад", "Кӯмаки Амрико вобастагии Аврупоро аз ИМА зиёд мекунад", "Нақшаи Маршалл барои назорати сиёсии Аврупо истифода мешавад"],
            ru: ["Европа самостоятельно справляется с послевоенным кризисом", "США оказывают экономическую помощь Европе для её восстановления", "Американская помощь усиливает зависимость Европы от США", "План Маршалла используется для политического контроля над Европой"],
            en: ["Europe copes with the post-war crisis on its own", "The USA gives Europe economic aid to rebuild", "American aid makes Europe more dependent on the USA", "The Marshall Plan is used for political control over Europe"] } },
];
